### ISSUE TITLE
skills wont strengthening.

### ISSUE THREAD

**Issue by Bump-san** [ToranSharma/Duo-Strength#127]
The skill wont strengthening after i do 5 or even more than 10 practices, no matter if it only have 25% or even 75% strength.
for now i encounter this on "French for English" and "English for Indonesian", the skill back to 100% strength when i level up that skill, but there's no way to fix the skill that i have maxed out. 

I'm using Edge, but also happened on chrome
is it normal or just me ?

**Comment by ToranSharma** [comment]
Hi,

Sorry you are having this issue. The strength values themselves are not calculated by Duo Strength, but by Duolingo. They just being displayed by Duo Strength from the hidden information found in a user's 'extended profile' data which is requested from Duolingo.

A number of other users have been reporting this issue, even before Duo Strength was created, you can see more info on the forums:
- https://forum.duolingo.com/comment/8360889/Weak-words-with-1-year-since-practice-despite-doing-daily
- https://forum.duolingo.com/comment/32530790/Skills-refuse-to-strengthen-despite-multiple-attempts
- https://forum.duolingo.com/comment/31609272/Fix-that-bug-please
- https://forum.duolingo.com/comment/30806046/Skill-not-strengthening

Essentially it seems like there are long standing issues on Duolingo's end that cause this. Skill strengths are based in some way on the strengths of the words in that skill. Words themselves get strengthened when you get a question correct that is trying to teach you that word. However for some reason

**Comment by ToranSharma** [comment]
It is also worth checking your user on duome.eu by going to duome.eu/USERNAME/progress to check that it matches Duo Strength with the skills that need strengthening. If they differ there is likely to be an issue that I can fix.
