### ISSUE TITLE
duo strength not changing my red bars - using version 1.3.45

### ISSUE THREAD

**Issue by jim-cress** [ToranSharma/Duo-Strength#139]
no matter how many times i redo practice lessons bars do not change. Does my privacy setting have to be set to public? I don't want to do this because I do not want to play in the leagues.

![image](https://user-images.githubusercontent.com/78605026/107047813-3c56aa00-6796-11eb-8b8f-94024306cd98.png)

**Comment by ToranSharma** [comment]
Hi,

As far as I know a users privacy setting does not impact any of Duo Strength's functionality.

Skill strengths are not calculated by Duo Strength, but by duolingo's system; Duo Strength just displays these hidden values that can be accessed in a file requested from the duolingo API. Unfortunately, there is a long standing issue on duolingo's end that means that some skills never get back to 100% strength, or may take an extremely unreasonable number of practices. Maxed out skills e.g. Crown 2 Grammar skills or Crown 5 normal skills, are the worst for this.

The practice session seem to only include a limited set of the words for the skill. As a result some words or almost never included and so never strengthened, leading to the whole skill being stuck at below 100% strength.

You can find several posts complaining about various versions this on the forum, many from before I released Duo Strength. Here are a few that come up after a quick search:
https://forum.duolingo.com/comment/30893895/Skill-still-stuck-at-75-after-repeated-practice
https://forum.duolingo.com/comment/28436926
https://forum.duolingo.com/comment/30806046/Skill-not-strengthening
https://forum.duolingo.com/comment/33487911


### Future Workaround
In the development version that I am actively trying to finish up, there is a new feature that allows a user to mark skills as 'mastered'. This forces Duo Strength to ignore the duolingo strengths of those skills and display them as always 100% strength. This is meant particularly for situations like yours, where a very early skill that is Crown 5 (e.g. Intro) can be stuck as needing attention, despite you being well beyond needing to practise it.

To use this feature, a new button is added to skill popups for mark them as mastered. Once clicked the skill id is added to a list associated with the user, and before any other features process the strengths, these skills have their strengths set to 100%:
Before:
![Not-Mastered](https://user-images.githubusercontent.com/4559968/107064442-68dce700-67d3-11eb-9d74-bb116ab7d0c3.png)
After:
![Mastered](https://user-images.githubusercontent.com/4559968/107064440-68445080-67d3-11eb-9142-e373d93392cf.png)

I hope to get the rest of the changes I am working on finished as soon as possible so that I can release a fairly large update, including this feature.

I hope this helps explain,

Toran

**Comment by jim-cress** [comment]
WOW, i appreciate you getting back to me so quickly! how will I know when this new version is available?

**Comment by ToranSharma** [comment]
No problem.

I will make a post about the update on the duolingo forums on release. I can also make a note to reply to this comment chain too so you get an email notification.

As I think you know, you can check the version number in the options popup shown when you click on the Duo Strength icon in your browser's toolbar.
![image](https://user-images.githubusercontent.com/4559968/107066300-b1959f80-67d5-11eb-85cf-fff86f8c0202.png)

The update will either be something other than 1.3.x, i.e. 1.4.0 or 2.0.0. I am not sure currently which it will be under.

**Comment by jim-cress** [comment]
Awesome many thanks, when do you anticipate the update being done?

**Comment by ToranSharma** [comment]
Hopefully in the next couple of weeks, definitely before the end of the
month.

**Comment by jim-cress** [comment]
AWESOME! have a great weekend

**Comment by jim-cress** [comment]
Looking forward to this update, any word on launch yet?

**Comment by ToranSharma** [comment]
Just need to finish the last few changes in the redesigned options menu, which I plan to do tomorrow, and that should be it for new features. A bit of testing is needed to make sure all is well and I should be ready to release. I have to write release notes and the Duolingo forum post too. Maybe looking at a Monday release if I get enough time this weekend.

**Comment by jim-cress** [comment]
Awesome! Thank you so much.

**Comment by ToranSharma** [comment]
Duo Strength v2.0.0 out now! See the new post for more details: https://forum.duolingo.com/comment/47298041

**Comment by jim-cress** [comment]
You are the best, i have 127 skills to upgrade!

**Comment by jim-cress** [comment]
downloaded the extension, works awesome, lots of features. EXCELLENT! many
thanks

**Comment by ToranSharma** [comment]
I'm glad you like it!

Any issues let me know.

Toran

**Comment by jim-cress** [comment]
i really like the total strength bar, nice work

**Comment by jim-cress** [comment]
I have been playing with all the options, looks fantastic, 1 thing - you
have a hide mastered skills button at bottom of tree, once turned on you
have to go to extension option to turn off again.

Any thing that you can do to help me spend 7700 lingots? that would be
great if there was something to buy in the store...

Great extension, i appreciate your developement

**Comment by ToranSharma** [comment]
I'm not quite sure which feature you mean. the mastered skills button is in the skill popout here:
![Mastered Skill](https://toransharma.com/i/Duo-Strength/v2.0/mastered-skill.png)

If you have the option enabled that make the tree only display skills that need attention (cracked, needs strengthening etc.) then there is a button which will reveal those skills again, like at the bottom of this screenshot:
![Show Only Needs Attention](https://toransharma.com/i/Duo-Strength/v2.0/show-only-needs-attention.png)

This button is just a temporary reveal, a page change of any kind will make the tree go back to only showing those skills that need attention again.


> Any thing that you can do to help me spend 7700 lingots? that would be great if there was something to buy in the store...
I've just gone over 10k myself, nothing I can do about them really, I think the lingot stuff is all done on Duolingo's servers. I don't think I can even just delete them.

**Comment by jim-cress** [comment]
OK gotch, it was the button on the bottom by the owl.

**Comment by jim-cress** [comment]
Is there a newer version that i need to download?

[image: image.png]

notice duo strength is on in the top but not appearing, only since duolingo
added purple legendary levels.

Jim Cress
1-705-280-9076
