### ISSUE TITLE
Duo strength not calculating current rate correctly

### ISSUE THREAD

**Issue by jim-cress** [ToranSharma/Duo-Strength#189]
see below, i have all skills up to level 3, the current rate calculator still believes that i have 21 days to reach level 3... therefore not calculating correctly.
![image](https://user-images.githubusercontent.com/78605026/134921907-e30700d1-c72a-48f9-8747-ce83b00873aa.png)
also my total strength is at 100% with no cracked skills
![image](https://user-images.githubusercontent.com/78605026/134922044-ba03522a-e3fe-4f31-852b-0f88327d9d06.png)
my cell phone (android) correctly shows 3 crowns out of 5 below the owl trophy.

Jim

**Comment by ToranSharma** [comment]
Hi Jim,

Your tree level is showing as L2 because of you have 27 grammar skills at L2, which since the legendary update, be made L3. It is up for debate if you include the grammar skills in the tree level calculation. I include them because of the fact that they have to be completed to unlock the skills below when first finishing the tree. As a result, for the for the tree to ever become finished (L1) you need to get those skills to L1, so they need to be included then. To be consistent they continue to be factored into the tree level calculation for the subsequent levels. Before legendary, they were ignored once they were at L2 because that is as high as they went, so they would forever keep the tree level at 2 if not ignored past that point. Now that they can become legendary or L3, I have moved the point at which they factor up to L3.

I haven't used the duolingo app in sometime so I didn't know Duolingo themselves had any sort of tree level indication. It seems they either haven't updated their tree level calculations, or never included grammar skills from the start. Duome.eu seems to have followed the same logic as I have with Duo Strength as can be seen in the screenshot below for your spanish tree:

![image](https://user-images.githubusercontent.com/4559968/134931159-9b26ddbd-6747-4753-bd28-0cdddae815f3.png)

Those 108 sessions are all the legendary tests needed to get your 27 L2 grammar skills to L3. 27 skills * 4 tests = 108 sessions. Duo Strength should show the same thing if you hover over the dotted underlined current rate in the prediction. The prediction algorithm Duo Strength uses is a bit different from duome which is why there is a discrepancy between the number of days predicted (19 days vs 21 days).

I hope that helps explain what is going on.

Toran

**Comment by ToranSharma** [comment]
Purple is the new gold it seems! Yes that is correct, once all skills are at least L3 your tree will be L3. The prediction will then switch over to showing how long to get to L4, using the rate of lessons completed on L3 skills for the prediction.

**Comment by jim-cress** [comment]
Purple is the new gold, is that like orange is the new black? Ahahahaha
thank you, i will purple the grammer sections. Have a great day!
