### ISSUE TITLE
None of Duo Strength's features are appearing despite being enabled

### ISSUE THREAD

**Issue by VictoryStar527** [ToranSharma/Duo-Strength#219]
I'm using Chrome on Windows 10.
![Screenshot 2022-09-17 14 48 15](https://user-images.githubusercontent.com/49041962/190872198-75707d09-74e7-49b4-99c0-117cb3d86876.png)

**Comment by ToranSharma** [comment]
Thanks for reporting, I'm taking a look now.

**Comment by ToranSharma** [comment]
@VictoryStar527 I have just published v2.0.29 which should hopefully fix this issue caused by the new Duolingo layout.

This is available now for firefox, but is still awaiting approval for chrome/opera/edge. This should only take a couple of hours.

You can check which version you have by opening the Duo Strength extension options popup, where it should be displayed in the top right.

Any more issues, let me know.

Toran
