### ISSUE TITLE
extension icon not shown in Yandex browser 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#34]
fyi : extension icon not shown in Yandex browser  (i.e. in the top right corner) 
<img width="966" alt="Screen Shot 2020-01-29 at 11 41 59" src="https://user-images.githubusercontent.com/60418150/73328459-6aa0d000-428c-11ea-8df5-762e7bac728a.png">

**Comment by ToranSharma** [comment]
Hi @alexseyk,

I believe this is a result of the extension being a content script, rather than a page or browser action. For example, the icon is not displayed in the tool bar in Firefox either and it is always greyed out in Opera.

The only thing this really impacts is the ease of getting to the options page. I have had the intention for a while to add a setting button somewhere on the duolingo page to solve this.

I could perhaps modify the extension to be a page action rather than a content script, but I am not sure that I can see much advantage as I don't think Duo Strength really fits a page action type of extension.

Toran

**Comment by alexseyk** [comment]
Toran
Oh, Ok I guess it's an expected behavior then :) 
It works perfectly fine under Chrome which  i was comparing to.
May be add a button or two on the page to show / hide Cracked and Needs Strengthening suggestions?
I can't imagine the need to modify Options very often once they are set. 
Alex

**Comment by ToranSharma** [comment]
Hi again Alex,

Having thought about this more and had another user contact me asking if there is a way to display the icon in the toolbar on Firefox. I think I will change Duo Strength to be page action, and have the options page shown in a popup box when the icon is clicked. This should make the icon appear for all browsers, and will also make access to the options page quicker and easier, though as you point out, I don't believe most users access the options page very often at all.

To make the experience smoother I may also make the content added to the page be refreshed when a change is made to the options, rather than having to refresh the page to see the changes.

I will work on this shortly and include it in v1.3.

Toran

**Comment by alexseyk** [comment]
Toran 
From the end user perspective I doubt if there is a difference between page action or content script. Personally i think that extension is simper than a script since it does not require prior installation of tapermonkey or similar. 

With regard to options have you looked at Duolingo Tree Enhancer ? it has options on the page 
https://github.com/camiloaa/duolingotreeenhancer

**Comment by ToranSharma** [comment]
No, the aim wouldn't be for users to notice any difference, other than the Duo Strength icon appearing consistently in the browser toolbar across all the browsers. I am of course leaving Duo Strength as a browser extension, adding the page_action key to the manifest file will simply allow me to control the fact that the icon should be displayed in the toolbar and allow me to choose the action that is taken when it is clicked.

I had another user point me to that userscript relating to some of its features. I could also add a way to display the options page in the page itself somewhere. I feel that having the options in the popup window on clicking the icon is just as easy.

**Comment by ToranSharma** [comment]
The page action change has been added in 8c84b53.

This adds the Duo Strength logo to the toolbar of all browsers. Clicking the logo brings up the options page in a popup, and changing any of the options, reloads the extension to reflect the change.
