### ISSUE TITLE
Visual suggestion for the strengh bars

### ISSUE THREAD

**Issue by comproperty247** [ToranSharma/Duo-Strength#5]
As I have also my own extension (still on developing), I added one extra style above your extension when my extension is running 

Please try to add this css line to head > style  and see if you like it. 

.strengthBarHolder > div:last-child {  position: absolute;  left: 37%;  width: 25% !important;  color: #fff;  font-size: 0.8em;}

Is just a visual suggestion, not a issue 

Regards,
Carlos

**Comment by ToranSharma** [comment]
Hi again,

After I did #4 I'll have a look at your suggestion. I have a couple of new feature idea that I want to to test out so I may include this with any of them that I think work.

Thanks,

Toran

**Comment by comproperty247** [comment]
Ok, great! ;-)

Regards,
Carlos

**Comment by ToranSharma** [comment]
I had a look at this around when the issue was opened but I am finally getting round to addressing it now.

I think that it looks good when skills are at 100%. However, I think that at less than 100% strength, centralising the bar and the percentage means that it is no longer clearly a progress bar that has space to fill. The bar would expand from the middle on both sides equally, I think the progress element is more obvious when it starts at the left and fills up towards the right.

This could be made more obvious by adding a background element showing the width of a full bar, clearly showing the space that the bar as left to expand into.

Here is an example of what this looks like:
![](http://toransharma.com/i/2019-06-17_16-22-39.png)

I think I like how this looks, but I will add the option to turn the bar background on and off, with it on by default.

These changes have been made as of b259ac5a774538bb7c414bd3c855337d6911f12b.

Regards,

Toran
