### ISSUE TITLE
Suggestion: Link Show/Hide Button and Hotkey 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#68]
<img width="361" alt="Screen Shot 2020-04-25 at 12 28 39" src="https://user-images.githubusercontent.com/60418150/80272073-7b78aa80-86f0-11ea-9be8-93cc63f34b29.png">

Suggestion: Link Show/Hide Button and Hotkey  & Make 2nd pressing of hotkey to hide text again
<img width="743" alt="Screen Shot 2020-04-25 at 12 34 30" src="https://user-images.githubusercontent.com/60418150/80272165-29845480-86f1-11ea-87c3-128cbb92341e.png">
After i use hotkey to unhide the text it is strange to see that button behavior did not change
<img width="735" alt="Screen Shot 2020-04-25 at 12 34 16" src="https://user-images.githubusercontent.com/60418150/80272172-415bd880-86f1-11ea-872a-7fe2a0d1029f.png">

I understand that button sets a global behavior, while hotkey a local one, so call it a feature and explain it  in  the FAQ :)

**Comment by ToranSharma** [comment]
Yeah as you say, the hotkey is just to reveal that sentence so you can see what it is if it was too hard. This so that you don't have to use the mouse to click on the sentence, especially thinking about timed practice here. Subsequent sentences will be unaffected.

I cannot really see a use to rehiding with the hotkey, once you have revealed it you know the sentence. I could add a different hotkey to toggle the hiding setting itself, but given the button is there I don't see that this offers much of an advantage as it isn't something I expect users will be clicking very often so it isn't critical to save time on this action.

I think to make it clearer, before I put the time into writing the wiki on all the features their behaviour, I can change the hotkey options label to:  
"Enable Hotkey to unhide current sentence"

I hope that helps clear it up a little

**Comment by alexseyk** [comment]
Thank you

**Comment by ToranSharma** [comment]
This has been changed in af90f61 and will be released in v1.3.7
