### ISSUE TITLE
Language flag border not updated 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#70]
I recently got to L1 in Latin, and flag language border was not updated 
In a day or two i'll get to L2 and will keep you posted. 
<img width="613" alt="Screen Shot 2020-05-02 at 08 46 04" src="https://user-images.githubusercontent.com/60418150/80852299-9e0b4600-8c51-11ea-8d8a-7b06937f335a.png">

**Comment by ToranSharma** [comment]
Hmm, strange that it hasn't worked for Latin, but it has for the Ukrainian tree which has the blue border showing that it is L1.
___
Would you be able to try the following for me when you are on your Latin tree:
1. Open the devtools.

2. Go to the console tab, or use the console box in the bottom half if it is open.

3. Change the JavaScript context to Duo Strength. the default is top, if you click that there should be a Duo Strength option in the down down menu:
![image](https://user-images.githubusercontent.com/4559968/80870289-7510a280-8c9d-11ea-8f5f-d178baafa667.png)

4. Then type or paste the following line and hit enter:
`console.table(progress)`
___
Hope fully you should get a table printed out, something like this:
![image](https://user-images.githubusercontent.com/4559968/80870363-e7818280-8c9d-11ea-9783-75ed25208d1f.png)


A screenshot of this table would be very useful in working what is going on here. If it is quite long, then the important part is the bottom, rows with a larger index.

Thanks,

Toran

**Comment by alexseyk** [comment]
I "enabled" the flag borders since that feature become available. At that time Latin was at L0, and Ukrainian at L1;  Now i reached L1 in Latin and there was no update in color. 
Below is requested screen shot.
<img width="1108" alt="Screen Shot 2020-05-03 at 08 06 36" src="https://user-images.githubusercontent.com/60418150/80896190-22270180-8d16-11ea-85db-925ed823b99c.png">

Also it seem that flag border do not work for mobile-web view. I switched to Ukrainian and got some more errors 
<img width="1112" alt="Screen Shot 2020-05-03 at 08 08 04" src="https://user-images.githubusercontent.com/60418150/80896193-27844c00-8d16-11ea-9777-6b456938fa84.png">

**Comment by ToranSharma** [comment]
Thanks for the information. From what I can see from the screenshot, the progress information is being saved correctly, you can see in the middle column the transition from 0 to 1, this is where the tree level is stored. There must be an issue with how the data is being pulled out of storage at the time of trying to add the borders.

I will see what I can find.

Regarding the flag borders while in mobile layout, I never added this features due to duolingo using a border to indicate which language is active. You can see this in your first screenshot, where Latin has a blue border.

This is not Duo Strength, you would see this even if the extension is disabled. For example my L0 Spanish tree in mobile layout with Duo Strength disabled.
![image](https://user-images.githubusercontent.com/4559968/80913273-5c56ca00-8d3b-11ea-9f7e-fae0ed045788.png)

I suppose I could overwrite this border feature and show the current language by having it shaded with a differently shaded background, like in the desktop layout:
![image](https://user-images.githubusercontent.com/4559968/80913310-9f18a200-8d3b-11ea-83e1-3b5200982c46.png)

That is something I'll have to look into, but at the time of developing the flag borders feature, I decided that it wasn't worth doing right away.

**Comment by ToranSharma** [comment]
> Also it seem that flag border do not work for mobile-web view. I switched to Ukrainian and got some more errors
> <img alt="Screen Shot 2020-05-03 at 08 08 04" width="1112" src="https://user-images.githubusercontent.com/60418150/80896193-27844c00-8d16-11ea-9777-6b456938fa84.png">

Regarding the errors you are seeing in this screenshot. I think the extension context invalidated ones come from the extension having been updated while you had that window open. I get these while testing, every time I reload the extension after updating the code, anything the old version tries to do will cause an error as it is no longer valid.

**Comment by ToranSharma** [comment]
I think I have found the issue. As your screenshot suggested, the information was being stored correctly, but not being retrieved for Latin. I'm not sure if this was an error on my part, or a Duolingo change that is causing this, but the detection for the Latin and Gaelic flags was incorrect.

This should be fixed in 8646048.
