### ISSUE TITLE
Site access 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#81]
Can you modify site access to ` https://*.duolingo.com/*` and \ or add `https://preview.duolingo.com/*`

FYI: **preview** is used for b-testing. apparently new version is released every Thursday and pushed to everyone on Monday. So far they don't tell us what are the new improvements :(

**Comment by ToranSharma** [comment]
Hi,

I can widen the access of Duo Strength to add the preview subdomain.

I am hesitant to widen it to all subdomains as this would include the forums, for which I would need to add more checks to prevent errors. In the future I may do this is so that I can add new features to the forum pages, or at least make some of the current features function there, like the crowns breakdown etc.

An update with this change, may take longer to be approved due to possible, security concerns.

Toran

**Comment by ToranSharma** [comment]
Change made in 5ab18f4

**Comment by alexseyk** [comment]
Thanks. I agree that there is no reason to give access to all subdomains. I just noticed that other extensions do so and was wondering why. On the other hand, those extensions in question, work / initiate  only during the lessons / tests, so probably it does not  matter if they have a wider access since (probably) nothing triggers on other pages.
